### ISSUE TITLE
Missing maec.utils.idgen module

### ISSUE THREAD

**Issue by abulhol** [MAECProject/python-maec#74]
I have just started working python-maec, installed the required dependencies and tried out the examples, but some classes and methods are missing. 
In particular, the idgen module is missing (see http://maec.readthedocs.org/en/stable/api/utils/idgen.html), and I cannot find the functions set_id_namespace and set_id_method 
(see example from manual here: http://maec.readthedocs.org/en/stable/examples.html)
Where have they gone?

**Comment by ikiril01** [comment]
Hi @abulhol, these modules have all been moved to the [mixbox](https://github.com/CybOXProject/mixbox) library. Python-maec is still in the process of being updated to use mixbox, so I'd recommend using the latest official release, [4.1.0.12](https://github.com/MAECProject/python-maec/releases/tag/v4.1.0.12).

**Comment by abulhol** [comment]
Thanks for the fast reply. I found the module in mixbox, but of course it is a bit difficult to follow the manual this way. I got the example working like this (have to improve on my Python skills and how to write the import statements properly...)

```
from maec.package import Package, MalwareSubject
import mixbox

mixbox.idgen.set_id_method(mixbox.idgen.IDGenerator.METHOD_INT)
p = Package()
ms = MalwareSubject()
p.add_malware_subject(ms)

print p.to_xml(include_namespaces=False)
```

**Comment by ikiril01** [comment]
Glad you got it working! We'll have to update the documentation to take into account the mixbox-related changes :)

**Comment by bworrell** [comment]
Posting a comment here because it's super related to an issue I posted in python-stix yesterday:  https://github.com/STIXProject/python-stix/issues/280 :D

I agree with everything @ikiril01 said and generally speaking, sticking to the official releases on [PyPI](https://pypi.python.org/pypi/maec) is a safer bet than writing code against the latest commit on `master`, especially right now since we are in a heavy development cycle right now.

Thanks for posting the issue and glad to see you got things working! We're cranking away at all this stuff so it should hopefully stabilize a lot more in the near future!

**Comment by abulhol** [comment]
Hi guys,
I wrote a converter based using python-maec and am now testing it on Ubuntu.
I installed maec using pip
```pip install maec```
which installed version 2.1.0.13.dev2 (and also cybox as a dependency)
However, my converter failed because it could not find maec.utils.idgen
I then ran
```pip install maec==2.1.0.12```
but I still had problems because some classes from cybox could not be found, so I then uninstalled everything again and explicitly ran 
```
pip install cybox==4.1.0.12
pip install maec==2.1.0.12
```
With this, my converter finds all imports, but I guess something needs to be fix in PyPI?!

**Comment by ikiril01** [comment]
Hi @abulhol, thanks for reporting this. I thought that the 'dev' releases were hidden so they shouldn't be installed with `pip install maec`, but looks like we need to double-check on this.

**Comment by abulhol** [comment]
PyPI is messed up a bit at the moment anyway, if you look for maec or cybox using the "search" box, it won't find them.

**Comment by gtback** [comment]
@abulhol: What version of pip? I seem to remember that some versions of pip installed "pre-release" versions (like 2.1.0.13.dev2) of packages by default, but that's no longer the case. 

@ikiril01: I'm not sure if "hiding" a package on PyPI actually keeps pip from downloading them. I know you can explicitly request an old version (like maec=4.1.0.0), and I'm pretty sure "hiding" only affects the web interface. Try `pip install maec==99999` to see the versions available.

**Comment by abulhol** [comment]
@gtback: On Ubuntu, I use python-pip 1.0-1build1 (with Python 2.7) I have not changed any settings for pip, so it seems to be the default behavior.

**Comment by gtback** [comment]
That version of pip is pretty old (the latest is 7.1.2, but Ubuntu typically lags behind that quite a bit). That explains why `pip install maec` gave you the development version. Older versions of pip didn't distinguish and would always install the newest, development or not.

While the mixbox refactor is ongoing, you'll need to explicitly install the specific versions of cybox (4.1.0.12) and maec (2.1.0.12) like you did above, or upgrade to a newer version of pip.

**Comment by abulhol** [comment]
Thanks for looking into this!
