### ISSUE TITLE
Add behavior bug in bundle.py

### ISSUE THREAD

**Issue by geosakel77** [MAECProject/python-maec#76]
Good morning I think that the add_Behavior() in line 569 of bundle.py  should be changed to add_behavior()

'''
Traceback:
File "build/bdist.linux-x86_64/egg/maec/bundle/bundle.py", line 569, in add_behavior
AttributeError: 'BehaviorCollection' object has no attribute 'add_Behavior'
'''

**Comment by ikiril01** [comment]
@geosakel77 thanks for the bug report!
