### ISSUE TITLE
collections is not callable in bundle.py line 577

### ISSUE THREAD

**Issue by geosakel77** [MAECProject/python-maec#77]
In line 577 there is
 if not self.collections():
 I think  that should be changed to  
 if not self.collections:
Traceback
File "build/bdist.linux-x86_64/egg/maec/bundle/bundle.py", line 577, in add_named_candidate_indicator_collection
TypeError: 'Collections' object is not callable

**Comment by ikiril01** [comment]
@geosakel77 thanks for the bug report!
