### ISSUE TITLE
Mix API with bindings (AnalysisSystem)

### ISSUE THREAD

**Issue by abulhol** [MAECProject/python-maec#80]
Hi, it is me again :-)
I am trying to add data on the AnalysisEnvironment -> AnalysisSystems. It seems that the API for AnalysisSystem is not complete, I can only see installed_programs being set in analysis.py

So I have been trying for a while, first like this: 
<pre>system = AnalysisSystemType()
opsys = OSType()
opsys_name = cybox_common.StructuredTextType(valueOf_='Windows XP')
opsys.set_Description(opsys_name)
system.set_OS(opsys)

analysis.analysis_environment = AnalysisEnvironment()
analysis.analysis_environment.analysis_systems = AnalysisSystemList()
analysis.analysis_environment.analysis_systems.append(system)</pre>
which gave me: 
```Can't put '<maec.bindings.maec_package.AnalysisSystemType object at 0x00000000048B3C18>' (<class 'maec.bindings.maec_package.AnalysisSystemType'>) into a <class 'maec.package.analysis.AnalysisSystemList'>```

Then like this: 
<pre>opsys = OSType()
opsys_name = cybox_common.StructuredTextType(valueOf_='Windows XP')
opsys.set_Description(opsys_name)
sys = AnalysisSystem()
sys.os = opsys

analysis.analysis_environment = AnalysisEnvironment()
analysis.analysis_environment.analysis_systems = AnalysisSystemList()
analysis.analysis_environment.analysis_systems.append(sys)</pre>
which returned:
```__init__() takes exactly 1 argument (2 given) ```
(related to the sys.os = opsys)

Why does it say that 2 arguments were given? And what is the correct way to go here?

**Comment by ikiril01** [comment]
Hi @abulhol :)

Actually, the `AnalysisSystem` class inherits from the `System` class (cybox.objects.system), so you should be able to use the API classes to do what you need:

```python
from maec.package import Analysis, AnalysisEnvironment, AnalysisSystem, AnalysisSystemList
from cybox.objects.system_object import OS
from cybox.common import PlatformSpecification, PlatformIdentifier

# OS/Platform Specification
os = OS()
pi = PlatformIdentifier()
pi.value = "Windows XP"
ps = PlatformSpecification()
ps.identifiers = [pi]
os.platform = ps

# Analysis/Environment Specification
asys = AnalysisSystem()
asys.os = os
asyslist = AnalysisSystemList()
asyslist.append(asys)
aenv = AnalysisEnvironment()
aenv.analysis_systems = asyslist
a = Analysis()
a.analysis_environment = aenv
```

Let me know if that works!

**Comment by abulhol** [comment]
Yes, it does! It seems I need some more practice in chaining the objects the right way. Will look at it in more detail tomorrow (evening over here in Europe).
